import {useState,useEffect,useContext} from 'react'
import Link from "next/link"
import Head from "next/head"


// type Props = {
//     ecommercePosts: Post[]
// }

export default function MariaValtorta() {

    // useEffect(() => { 

    // }, [])
    
    return <>
        <Head>
        <title>Create Next Appppp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="youtubeChannel">
        ...........contenu à remplir ici yt...........
        </main>
    </>
}
