export const FLYER_TEMPLATES = [
  {
    id: 'retraite_weekend',
    name: '✝️ Retraite Spirituelle de Weekend',
    category: 'sanctuaire',
    format: 'story',
    width: 1080,
    height: 1920,
    headerTag: 'SANCTUAIRE NOTRE-DAME DU ROSAIRE DE BOLOBI',
    mainTitle: 'GRANDE RETRAITE SPIRITUELLE',
    subtitle: 'Du Vendredi 15 au Dimanche 17 Septembre 2026',
    description: 'Venez vous ressourcer au cœur de la nature. Temps de prière, confessions, adorations et enseignements spirituels.',
    pricing: 'Formule Repas & Hébergement dès 3 000 FCFA / jour',
    contact: '📞 Infoline & Réservations : 07 09 36 06 72 / 07 79 28 82 93',
    primaryColor: '#c9a84c',
    secondaryColor: '#0f172a',
    bgGradient: 'linear-gradient(135deg, #0f172a 0%, #1e293b 100%)',
    bgImageUrl: '/images/hero-bolobi.jpg'
  },
  {
    id: 'promo_boutique',
    name: '🛍️ Promotion Boutique & Rosaires',
    category: 'ecommerce',
    format: 'square',
    width: 1080,
    height: 1080,
    headerTag: 'BOUTIQUE OFFICIELLE DU SANCTUAIRE',
    mainTitle: 'ROSAIRES & OBJETS DE PIÉTÉ',
    subtitle: 'Nouveaux Arrivages Bénis',
    description: 'Découvrez nos chapelets en bois d\'iroko, livres de prière, médailles et bougies de dévotion.',
    pricing: 'Livraison disponible sur Abidjan & Adzopé',
    contact: '📲 Commandes WhatsApp : 07 09 36 06 72',
    primaryColor: '#d97706',
    secondaryColor: '#451a03',
    bgGradient: 'linear-gradient(135deg, #451a03 0%, #78350f 100%)',
    bgImageUrl: ''
  },
  {
    id: 'communique_officiel',
    name: '📢 Communiqué Officiel du Sanctuaire',
    category: 'sanctuaire',
    format: 'a4',
    width: 1240,
    height: 1754,
    headerTag: 'COMMUNIQUÉ DU DIRECTEUR DU SANCTUAIRE',
    mainTitle: 'PROGRAMME DES CELEBRATIONS',
    subtitle: 'Sanctuaire Notre-Dame du Rosaire de Bolobi (Adzopé)',
    description: 'Le Père Gilbert et l\'équipe d\'animation pastorale vous informent du calendrier officiel des messes, récollections et temps d\'écoute spirituelle pour ce mois.',
    pricing: 'Entrée libre et ouverte à tous les pèlerins',
    contact: '📍 Bolobi, Route d\'Adzopé | ✉️ puissancedamour@yahoo.fr',
    primaryColor: '#2563eb',
    secondaryColor: '#0f172a',
    bgGradient: 'linear-gradient(135deg, #0f172a 0%, #1e3a8a 100%)',
    bgImageUrl: ''
  },
  {
    id: 'celebration_mariale',
    name: '🌹 Pèlerinage & Fête Mariale',
    category: 'evenement',
    format: 'story',
    width: 1080,
    height: 1920,
    headerTag: 'GRAND PÈLERINAGE MARIAL',
    mainTitle: 'NOTRE-DAME DU ROSAIRE',
    subtitle: 'Rassemblement Diocésain & Prière pour la Paix',
    description: 'Processions aux flambeaux, récitation du Saint Chapelet, messe solennelle d\'action de grâce et prières de guérison.',
    pricing: 'Possibilité d\'hébergement en dortoir ou chambre',
    contact: '📞 Infoline : 07 09 36 06 72',
    primaryColor: '#ec4899',
    secondaryColor: '#831843',
    bgGradient: 'linear-gradient(135deg, #831843 0%, #500724 100%)',
    bgImageUrl: ''
  }
];
