import {useContext} from 'react'
import Link from "next/link";
import AuthContext from "../stores/authContext.js"
import Head from "next/head"
import Nav from '../components/Nav'

export default function Ecommerce() {
    const {ok} = useContext(AuthContext)
    , id=3

    return <>
        <Head>
        <title>Create Next Appppp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>


        <Nav />


        <main className="vente">
            <section>
                <button>Publications chrétiennes</button>
                <button>Objets de piété</button>
                <select>
                    <option value="">Choisir un type d'article</option>
                </select>
            </section>
            <article>
                <figure>
                    <img src="img/vente-religieuse/min/publication-puissance-divine/evangile-revele-maria-valtorta-1.webp" alt="dsfihdoi fdio hfds" />
                    <figcaption>L'Évangile Révélé à Maria Valtorta</figcaption>
                    <p>Coffret 1: La préparation (3 livrets)</p>
                    <span className="prix">7500 (fcfa => ::before)</span>
                    <Link href={"vente-en-ligne/"+id}>
                        <a target="_blank">open</a>
                    </Link>
                    <a href="#publication-chretienne____objet-piete-catholique=evangile-revele....">afficher article</a>
                </figure>
            </article>
        </main>
    </>
}
