import {useContext} from 'react'
import Head from "next/head";
import Image from "next/image";
import AuthContext from "../stores/authContext.js"
import Carousel from "../components/_/Carousel"
// import styles from '../styles/Home.module.css'

export default function Home() {
  const {ok} = useContext(AuthContext)

  return (
    <>
      <Head>
        <title>Create Next Appppp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <main className="">
        {/* {ok} */}
        <Carousel />

        
      </main>




    </>
  );
}
